#!/usr/bin/env bash
#
# Provision the Interview Tracker on a fresh Ubuntu server.
#
#     sudo ./deploy/install.sh
#
# Idempotent: safe to run again to upgrade an existing install. The database,
# the uploaded CVs and the generated password all survive a re-run — only the
# application code and its dependencies are replaced.
#
# What it sets up:
#
#   /opt/resume-filter          the application and its virtualenv
#   /var/lib/resume-filter/cvs  uploaded CVs (persists across upgrades)
#   postgresql                  a local database and a role that owns it
#   resume-filter.service       uvicorn on 127.0.0.1:8000, restarted on failure
#   nginx                       port 80 -> 127.0.0.1:8000
#
# The app is NOT exposed on 8000 directly: it binds loopback only, so nginx is
# the single way in and the only port that has to be open.

set -euo pipefail

APP_USER=resumefilter
APP_DIR=/opt/resume-filter
DATA_DIR=/var/lib/resume-filter
CV_DIR="$DATA_DIR/cvs"
DB_NAME=interview_tracker
DB_USER=resumefilter
ENV_FILE="$APP_DIR/.env"

SRC="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run this with sudo."
[[ -f "$SRC/app/main.py" ]] || die "Cannot find the application at $SRC."

# ── Packages ─────────────────────────────────────────────────────────
say "Installing packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    python3 python3-venv python3-dev \
    postgresql postgresql-client \
    nginx \
    build-essential libpq-dev \
    rsync curl

# ── Service account ──────────────────────────────────────────────────
# A system user with no shell and no home: this account exists to own the
# files and run one process, and should not be a way into the machine.
if ! id -u "$APP_USER" >/dev/null 2>&1; then
    say "Creating service user $APP_USER"
    adduser --system --group --no-create-home --shell /usr/sbin/nologin "$APP_USER"
fi

# ── Database ─────────────────────────────────────────────────────────
say "Setting up PostgreSQL"
systemctl enable --now postgresql

# Generate the password once and keep it. Re-running the installer must not
# invalidate the credentials a working deployment is already using.
if [[ -f "$ENV_FILE" ]] && grep -q '^PG_PASSWORD=' "$ENV_FILE"; then
    DB_PASSWORD="$(grep '^PG_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)"
    echo "    reusing the existing database password"
else
    DB_PASSWORD="$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)"
    echo "    generated a new database password"
fi

run_sql() { sudo -u postgres psql -v ON_ERROR_STOP=1 -qtAc "$1"; }

if [[ -z "$(run_sql "SELECT 1 FROM pg_roles WHERE rolname='$DB_USER'")" ]]; then
    run_sql "CREATE ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD'"
else
    run_sql "ALTER ROLE $DB_USER LOGIN PASSWORD '$DB_PASSWORD'"
fi
# CREATEDB so the app keeps its "creates its own database on first run"
# behaviour: if the database is ever dropped, starting the service rebuilds it.
run_sql "ALTER ROLE $DB_USER CREATEDB"

if [[ -z "$(run_sql "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'")" ]]; then
    run_sql "CREATE DATABASE $DB_NAME OWNER $DB_USER"
    echo "    created database $DB_NAME"
else
    echo "    database $DB_NAME already exists, leaving its contents alone"
fi

# ── Application files ────────────────────────────────────────────────
say "Installing the application to $APP_DIR"
mkdir -p "$APP_DIR" "$CV_DIR"
# --delete keeps an upgrade from leaving stale modules behind, but the
# virtualenv, the .env and the uploaded CVs are not ours to remove.
rsync -a --delete \
    --exclude '.venv/' --exclude '.env' --exclude 'data/' \
    --exclude '__pycache__/' --exclude '.pytest_cache/' --exclude '.git/' \
    "$SRC/" "$APP_DIR/"

# ── Configuration ────────────────────────────────────────────────────
say "Writing $ENV_FILE"
cat > "$ENV_FILE" <<ENV
# Generated by deploy/install.sh — edit freely, it is preserved on re-runs
# except for this header.

# ── PostgreSQL ───────────────────────────────────────────────────────
# Local server, reached over the loopback interface.
PG_HOST=127.0.0.1
PG_PORT=5432
PG_DATABASE=$DB_NAME
PG_USER=$DB_USER
PG_PASSWORD=$DB_PASSWORD
PG_SSLMODE=disable
PG_POOL_MAX=10

# ── CV storage ───────────────────────────────────────────────────────
# Outside $APP_DIR on purpose: an upgrade replaces the application
# directory, and uploaded CVs must not go with it.
CV_STORAGE_DIR=$CV_DIR
MAX_CV_MB=15

# ── Identity matching ────────────────────────────────────────────────
IDENTITY_AUTO_LINK_MIN_CONFIDENCE=0.85
IDENTITY_DEFAULT_PHONE_REGION=BD

# ── Server ───────────────────────────────────────────────────────────
# Loopback only. nginx is the way in; nothing should reach uvicorn directly.
HOST=127.0.0.1
PORT=8000
ENV
chmod 640 "$ENV_FILE"

# ── Virtualenv ───────────────────────────────────────────────────────
say "Building the virtualenv ($(python3 --version))"
if [[ ! -x "$APP_DIR/.venv/bin/python" ]]; then
    python3 -m venv "$APP_DIR/.venv"
fi
"$APP_DIR/.venv/bin/pip" install --quiet --upgrade pip wheel
if ! "$APP_DIR/.venv/bin/pip" install --quiet -r "$APP_DIR/requirements.txt"; then
    die "Dependency install failed — see the pip output above.
     Usually this is a pinned version with no wheel for $(python3 --version).
     requirements.txt is the place to fix it."
fi

chown -R "$APP_USER:$APP_USER" "$APP_DIR" "$DATA_DIR"

# ── systemd ──────────────────────────────────────────────────────────
say "Installing the service"
install -m 644 "$SRC/deploy/resume-filter.service" /etc/systemd/system/resume-filter.service
systemctl daemon-reload
systemctl enable resume-filter
systemctl restart resume-filter

# ── nginx ────────────────────────────────────────────────────────────
say "Configuring nginx"
# The page shown while uvicorn is still coming up after a reboot.
install -d -m 755 /var/www/resume-filter
install -m 644 "$SRC/deploy/starting.html" /var/www/resume-filter/__starting.html
install -m 644 "$SRC/deploy/nginx-resume-filter.conf" /etc/nginx/sites-available/resume-filter
ln -sfn /etc/nginx/sites-available/resume-filter /etc/nginx/sites-enabled/resume-filter
# The packaged default would otherwise answer on port 80 instead of us.
rm -f /etc/nginx/sites-enabled/default
nginx -t
systemctl enable nginx
systemctl reload nginx

# ── Firewall ─────────────────────────────────────────────────────────
if command -v ufw >/dev/null 2>&1 && ufw status | head -1 | grep -q active; then
    say "Opening port 80 in ufw"
    ufw allow 80/tcp >/dev/null
fi

# ── Did it actually come up? ─────────────────────────────────────────
say "Checking the service"
for _ in $(seq 1 20); do
    if curl -fsS --max-time 2 http://127.0.0.1/api/health >/dev/null 2>&1; then break; fi
    sleep 1
done

HEALTH="$(curl -fsS --max-time 5 http://127.0.0.1/api/health || echo '')"
if [[ "$HEALTH" != *'"ok":true'* ]]; then
    echo
    systemctl --no-pager --lines=30 status resume-filter || true
    die "The app is up but cannot reach its database. Health said: ${HEALTH:-<no response>}"
fi

IP="$(hostname -I | awk '{print $1}')"
cat <<DONE

  ────────────────────────────────────────────────────────────
   Interview Tracker is running.

     http://$IP

   Database : $DB_NAME on 127.0.0.1:5432 (user $DB_USER)
   CVs      : $CV_DIR
   Config   : $ENV_FILE
   Logs     : journalctl -u resume-filter -f

   Sample data:  sudo -u $APP_USER $APP_DIR/.venv/bin/python \\
                     $APP_DIR/seed_demo.py
  ────────────────────────────────────────────────────────────

DONE
